"""Contracts for immutable Sprint 3 retrieval artifacts."""

from retrieval_artifacts.contracts import (
    CANDIDATE_SCHEMA_VERSION,
    CandidateArtifact,
    CandidateEmbeddingArtifactRef,
    CandidateEntry,
    CorpusProvenance,
    DatasetProvenance,
    RetrieverProvenance,
)
from retrieval_artifacts.corpus_manifest import (
    CORPUS_MANIFEST_SCHEMA_VERSION,
    CorpusConstructionDependency,
    CorpusManifest,
    CorpusManifestEntry,
)
from retrieval_artifacts.producer import (
    CorpusRecord,
    RawCandidateResult,
    build_bm25_retriever_provenance,
    compute_corpus_records_integrity_sha256,
    compute_document_id_map_sha256,
    compute_index_fingerprint_sha256,
    corpus_provenance_from_corpus_manifest,
    document_content_sha256,
    produce_bm25_candidate_artifact,
    validate_corpus_dataset_binding,
    validate_corpus_records_against_manifest,
    validate_bm25_index_binding,
)
from retrieval_artifacts.sample_manifest import (
    SAMPLE_MANIFEST_SCHEMA_VERSION,
    SampleManifest,
    SampleManifestEntry,
    SampleSelectionDependency,
    dataset_provenance_from_sample_manifest,
    query_text_sha256,
    verify_manifest_sample,
)

__all__ = [
    "CANDIDATE_SCHEMA_VERSION",
    "CandidateArtifact",
    "CandidateEmbeddingArtifactRef",
    "CandidateEntry",
    "CorpusProvenance",
    "DatasetProvenance",
    "RetrieverProvenance",
    "CORPUS_MANIFEST_SCHEMA_VERSION",
    "CorpusConstructionDependency",
    "CorpusManifest",
    "CorpusManifestEntry",
    "CorpusRecord",
    "RawCandidateResult",
    "build_bm25_retriever_provenance",
    "compute_corpus_records_integrity_sha256",
    "compute_document_id_map_sha256",
    "compute_index_fingerprint_sha256",
    "corpus_provenance_from_corpus_manifest",
    "document_content_sha256",
    "produce_bm25_candidate_artifact",
    "validate_corpus_dataset_binding",
    "validate_corpus_records_against_manifest",
    "validate_bm25_index_binding",
    "SAMPLE_MANIFEST_SCHEMA_VERSION",
    "SampleManifest",
    "SampleManifestEntry",
    "SampleSelectionDependency",
    "dataset_provenance_from_sample_manifest",
    "query_text_sha256",
    "verify_manifest_sample",
]
